version: '3.8'

services:
  docs:
    build:
      context: ../..  # This should be set to two levels up from where the Dockerfile is, if that's where the folders you want to copy are located.
      dockerfile: apps/nextra/Dockerfile
    entrypoint: "sh -c 'cd apps/nextra && yarn prod-standalone'"
    environment:
      - API_URL=http://proxy:8000
      - NODE_ENV=production
