version: '3.8'

services:
  docs:
    image: "protofy/workspace"
    entrypoint: "sh -c 'cd apps/nextra && yarn dev-standalone'"
    ports:
      - 7600:7600
    environment:
      - API_URL=http://proxy:8080
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      
volumes:
  protofy_modules:
    external: true