version: '3.8'

services:
  admin-api:
    image: "protofy/workspace"
    entrypoint: "sh -c 'cd apps/admin-api && yarn dev-standalone'"
    ports:
      - 3002:3002
    environment:
      - MQTT_URL=mqtt://localhost:1883
      - API_URL=http://proxy:8080
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      
volumes:
  protofy_modules:
    external: true