version: '3.8'

services:
  admin-api:
    build:
      context: ../..  # This should be set to two levels up from where the Dockerfile is, if that's where the folders you want to copy are located.
      dockerfile: apps/admin-api/Dockerfile 
    entrypoint: "sh -c 'cd apps/admin-api && yarn prod-standalone'"
    environment:
      - MQTT_URL=mqtt://localhost:8883
      - API_URL=http://proxy:8000
      - NODE_ENV=production