version: '3'
services:
  builder:
    image: "protofy/workspace"
    entrypoint: "sh -c 'yarn && yarn prepare-dev'"
    volumes:
      - ../:/workspace
      - protofy_modules:/workspace/node_modules

volumes:
  protofy_modules:
    external: true