version: "3.8"

services:
  admin:
    image: "protofy/workspace"
    entrypoint: "sh -c 'cd apps/admin && yarn dev-standalone'"
    ports:
      - 3003:3003
    environment:
      - API_URL=http://proxy:8080
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      
volumes:
  protofy_modules:
    external: true