version: "3.8"

services:
  admin:
    image: "protofy/workspace"
    entrypoint: "yarn admin-dev"
    ports:
      - 3003:3003
    environment:
      - API_URL=http://proxy:8000
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
      
volumes:
  protofy_modules:
    external: true