version: '3.8'

services:
  api:
    image: "protofy/workspace"
    entrypoint: "yarn api-dev"
    ports:
      - 3001:3001
    environment:
      - MQTT_URL=mqtt://admin-api:1883
      - API_URL=http://proxy:8080
      - NODE_ENV=development
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules

volumes:
  protofy_modules:
    external: true